{ post:
   { name: 'post',
     label: 'Posts',
     hierarchical: false,
     public: true,
     showUi: true,
     _builtin: true,
     hasArchive: false,
     supports:
      { title: true,
        editor: true,
        author: true,
        thumbnail: true,
        excerpt: true,
        trackbacks: true,
        'custom-fields': true,
        comments: true,
        revisions: true,
        'post-formats': true },
     labels:
      { name: 'Posts',
        singularName: 'Post',
        addNewItem: 'Add New Post',
        editItem: 'Edit Post',
        viewItem: 'View Post',
        searchItems: 'Search Posts',
        parentItemColon: '',
        allItems: 'All Posts',
        menuName: 'Posts',
        nameAdminBar: 'Post' },
     cap:
      { editPost: 'edit_post',
        readPost: 'read_post',
        deletePost: 'delete_post',
        editPosts: 'edit_posts',
        editOthersPosts: 'edit_others_posts',
        publishPosts: 'publish_posts',
        readPrivatePosts: 'read_private_posts',
        read: 'read',
        deletePosts: 'delete_posts',
        deletePrivatePosts: 'delete_private_posts',
        deletePublishedPosts: 'delete_published_posts',
        deleteOthersPosts: 'delete_others_posts',
        editPrivatePosts: 'edit_private_posts',
        editPublishedPosts: 'edit_published_posts' },
     mapMetaCap: true,
     taxonomies:
      [ 'category',
        'post_tag',
        'post_format',
        'language',
        'post_translations' ] },
  page:
   { name: 'page',
     label: 'Pages',
     hierarchical: true,
     public: true,
     showUi: true,
     _builtin: true,
     hasArchive: false,
     supports:
      { title: true,
        editor: true,
        author: true,
        thumbnail: true,
        'page-attributes': true,
        'custom-fields': true,
        comments: true,
        revisions: true },
     labels:
      { name: 'Pages',
        singularName: 'Page',
        addNewItem: 'Add New Page',
        editItem: 'Edit Page',
        viewItem: 'View Page',
        searchItems: 'Search Pages',
        parentItemColon: 'Parent Page:',
        allItems: 'All Pages',
        menuName: 'Pages',
        nameAdminBar: 'Page' },
     cap:
      { editPost: 'edit_page',
        readPost: 'read_page',
        deletePost: 'delete_page',
        editPosts: 'edit_pages',
        editOthersPosts: 'edit_others_pages',
        publishPosts: 'publish_pages',
        readPrivatePosts: 'read_private_pages',
        read: 'read',
        deletePosts: 'delete_pages',
        deletePrivatePosts: 'delete_private_pages',
        deletePublishedPosts: 'delete_published_pages',
        deleteOthersPosts: 'delete_others_pages',
        editPrivatePosts: 'edit_private_pages',
        editPublishedPosts: 'edit_published_pages' },
     mapMetaCap: true,
     taxonomies: [ 'language', 'post_translations' ] },
  attachment:
   { name: 'attachment',
     label: 'Media',
     hierarchical: false,
     public: true,
     showUi: true,
     _builtin: true,
     hasArchive: false,
     supports: { title: true, author: true, comments: true },
     labels:
      { name: 'Media',
        singularName: 'Media',
        addNewItem: 'Add New Post',
        editItem: 'Edit Media',
        viewItem: 'View Attachment Page',
        searchItems: 'Search Posts',
        parentItemColon: '',
        allItems: 'Media',
        menuName: 'Media',
        nameAdminBar: 'Media' },
     cap:
      { editPost: 'edit_post',
        readPost: 'read_post',
        deletePost: 'delete_post',
        editPosts: 'edit_posts',
        editOthersPosts: 'edit_others_posts',
        publishPosts: 'publish_posts',
        readPrivatePosts: 'read_private_posts',
        read: 'read',
        deletePosts: 'delete_posts',
        deletePrivatePosts: 'delete_private_posts',
        deletePublishedPosts: 'delete_published_posts',
        deleteOthersPosts: 'delete_others_posts',
        editPrivatePosts: 'edit_private_posts',
        editPublishedPosts: 'edit_published_posts' },
     mapMetaCap: true,
     taxonomies: [ 'language', 'post_translations' ] },
  revision:
   { name: 'revision',
     label: 'Revisions',
     hierarchical: false,
     public: false,
     showUi: false,
     _builtin: true,
     hasArchive: false,
     supports: { author: true },
     labels:
      { name: 'Revisions',
        singularName: 'Revision',
        addNewItem: 'Add New Post',
        editItem: 'Edit Post',
        viewItem: 'View Post',
        searchItems: 'Search Posts',
        parentItemColon: '',
        allItems: 'Revisions',
        menuName: 'Revisions',
        nameAdminBar: 'Revision' },
     cap:
      { editPost: 'edit_post',
        readPost: 'read_post',
        deletePost: 'delete_post',
        editPosts: 'edit_posts',
        editOthersPosts: 'edit_others_posts',
        publishPosts: 'publish_posts',
        readPrivatePosts: 'read_private_posts',
        read: 'read',
        deletePosts: 'delete_posts',
        deletePrivatePosts: 'delete_private_posts',
        deletePublishedPosts: 'delete_published_posts',
        deleteOthersPosts: 'delete_others_posts',
        editPrivatePosts: 'edit_private_posts',
        editPublishedPosts: 'edit_published_posts' },
     mapMetaCap: true,
     taxonomies: [] },
  nav_menu_item:
   { name: 'nav_menu_item',
     label: 'Navigation Menu Items',
     hierarchical: false,
     public: false,
     showUi: false,
     _builtin: true,
     hasArchive: false,
     supports: { title: true, editor: true },
     labels:
      { name: 'Navigation Menu Items',
        singularName: 'Navigation Menu Item',
        addNewItem: 'Add New Post',
        editItem: 'Edit Post',
        viewItem: 'View Post',
        searchItems: 'Search Posts',
        parentItemColon: '',
        allItems: 'Navigation Menu Items',
        menuName: 'Navigation Menu Items',
        nameAdminBar: 'Navigation Menu Item' },
     cap:
      { editPost: 'edit_post',
        readPost: 'read_post',
        deletePost: 'delete_post',
        editPosts: 'edit_posts',
        editOthersPosts: 'edit_others_posts',
        publishPosts: 'publish_posts',
        readPrivatePosts: 'read_private_posts',
        read: 'read',
        deletePosts: 'delete_posts',
        deletePrivatePosts: 'delete_private_posts',
        deletePublishedPosts: 'delete_published_posts',
        deleteOthersPosts: 'delete_others_posts',
        editPrivatePosts: 'edit_private_posts',
        editPublishedPosts: 'edit_published_posts' },
     mapMetaCap: true,
     taxonomies: [ 'nav_menu' ] },
  custom_css:
   { name: 'custom_css',
     label: 'Custom CSS',
     hierarchical: false,
     public: false,
     showUi: false,
     _builtin: true,
     hasArchive: false,
     supports: { title: true, revisions: true },
     labels:
      { name: 'Custom CSS',
        singularName: 'Custom CSS',
        addNewItem: 'Add New Post',
        editItem: 'Edit Post',
        viewItem: 'View Post',
        searchItems: 'Search Posts',
        parentItemColon: '',
        allItems: 'Custom CSS',
        menuName: 'Custom CSS',
        nameAdminBar: 'Custom CSS' },
     cap:
      { editPost: 'edit_css',
        readPost: 'read',
        deletePost: 'edit_theme_options',
        editPosts: 'edit_css',
        editOthersPosts: 'edit_css',
        publishPosts: 'edit_theme_options',
        readPrivatePosts: 'read',
        deletePosts: 'edit_theme_options',
        deletePublishedPosts: 'edit_theme_options',
        deletePrivatePosts: 'edit_theme_options',
        deleteOthersPosts: 'edit_theme_options',
        editPublishedPosts: 'edit_css' },
     mapMetaCap: false,
     taxonomies: [] },
  customize_changeset:
   { name: 'customize_changeset',
     label: 'Changesets',
     hierarchical: false,
     public: false,
     showUi: false,
     _builtin: true,
     hasArchive: false,
     supports: { title: true, author: true },
     labels:
      { name: 'Changesets',
        singularName: 'Changeset',
        addNewItem: 'Add New Changeset',
        editItem: 'Edit Changeset',
        viewItem: 'View Changeset',
        searchItems: 'Search Changesets',
        parentItemColon: '',
        allItems: 'All Changesets',
        menuName: 'Changesets',
        nameAdminBar: 'Changeset' },
     cap:
      { editPost: 'customize',
        readPost: 'customize',
        deletePost: 'customize',
        editPosts: 'customize',
        editOthersPosts: 'customize',
        publishPosts: 'customize',
        readPrivatePosts: 'customize',
        read: 'read',
        deletePosts: 'customize',
        deletePrivatePosts: 'customize',
        deletePublishedPosts: 'customize',
        deleteOthersPosts: 'customize',
        editPrivatePosts: 'customize',
        editPublishedPosts: 'do_not_allow' },
     mapMetaCap: true,
     taxonomies: [] },
  oembed_cache:
   { name: 'oembed_cache',
     label: 'oEmbed Responses',
     hierarchical: false,
     public: false,
     showUi: false,
     _builtin: true,
     hasArchive: false,
     supports: { title: true, editor: true },
     labels:
      { name: 'oEmbed Responses',
        singularName: 'oEmbed Response',
        addNewItem: 'Add New Post',
        editItem: 'Edit Post',
        viewItem: 'View Post',
        searchItems: 'Search Posts',
        parentItemColon: '',
        allItems: 'oEmbed Responses',
        menuName: 'oEmbed Responses',
        nameAdminBar: 'oEmbed Response' },
     cap:
      { editPost: 'edit_post',
        readPost: 'read_post',
        deletePost: 'delete_post',
        editPosts: 'edit_posts',
        editOthersPosts: 'edit_others_posts',
        publishPosts: 'publish_posts',
        readPrivatePosts: 'read_private_posts',
        read: 'read',
        deletePosts: 'delete_posts',
        deletePrivatePosts: 'delete_private_posts',
        deletePublishedPosts: 'delete_published_posts',
        deleteOthersPosts: 'delete_others_posts',
        editPrivatePosts: 'edit_private_posts',
        editPublishedPosts: 'edit_published_posts' },
     mapMetaCap: true,
     taxonomies: [] },
  user_request:
   { name: 'user_request',
     label: 'User Requests',
     hierarchical: false,
     public: false,
     showUi: false,
     _builtin: true,
     hasArchive: false,
     supports: { title: true, editor: true },
     labels:
      { name: 'User Requests',
        singularName: 'User Request',
        addNewItem: 'Add New Post',
        editItem: 'Edit Post',
        viewItem: 'View Post',
        searchItems: 'Search Posts',
        parentItemColon: '',
        allItems: 'User Requests',
        menuName: 'User Requests',
        nameAdminBar: 'User Request' },
     cap:
      { editPost: 'edit_post',
        readPost: 'read_post',
        deletePost: 'delete_post',
        editPosts: 'edit_posts',
        editOthersPosts: 'edit_others_posts',
        publishPosts: 'publish_posts',
        readPrivatePosts: 'read_private_posts',
        read: 'read',
        deletePosts: 'delete_posts',
        deletePrivatePosts: 'delete_private_posts',
        deletePublishedPosts: 'delete_published_posts',
        deleteOthersPosts: 'delete_others_posts',
        editPrivatePosts: 'edit_private_posts',
        editPublishedPosts: 'edit_published_posts' },
     mapMetaCap: true,
     taxonomies: [] },
  wp_block:
   { name: 'wp_block',
     label: 'Blocks',
     hierarchical: false,
     public: false,
     showUi: true,
     _builtin: true,
     hasArchive: false,
     supports: { title: true, editor: true },
     labels:
      { name: 'Blocks',
        singularName: 'Block',
        addNewItem: 'Add New Block',
        editItem: 'Edit Block',
        viewItem: 'View Block',
        searchItems: 'Search Blocks',
        parentItemColon: '',
        allItems: 'All Blocks',
        menuName: 'Blocks',
        nameAdminBar: 'Block' },
     cap:
      { editPost: 'edit_block',
        readPost: 'read_block',
        deletePost: 'delete_block',
        editPosts: 'edit_posts',
        editOthersPosts: 'edit_others_posts',
        publishPosts: 'publish_blocks',
        readPrivatePosts: 'read_private_blocks',
        read: 'edit_posts',
        deletePosts: 'delete_blocks',
        deletePrivatePosts: 'delete_private_blocks',
        deletePublishedPosts: 'delete_published_posts',
        deleteOthersPosts: 'delete_others_posts',
        editPrivatePosts: 'edit_private_blocks',
        editPublishedPosts: 'edit_published_posts' },
     mapMetaCap: true,
     taxonomies: [ 'language', 'post_translations' ] },
  polylang_mo:
   { name: 'polylang_mo',
     label: 'Strings translations',
     hierarchical: false,
     public: false,
     showUi: false,
     _builtin: false,
     hasArchive: false,
     supports: { title: true, editor: true },
     labels:
      { name: 'Strings translations',
        singularName: 'Strings translations',
        addNewItem: 'Add New Post',
        editItem: 'Edit Post',
        viewItem: 'View Post',
        searchItems: 'Search Posts',
        parentItemColon: '',
        allItems: 'Strings translations',
        menuName: 'Strings translations',
        nameAdminBar: 'Strings translations' },
     cap:
      { editPost: 'edit_post',
        readPost: 'read_post',
        deletePost: 'delete_post',
        editPosts: 'edit_posts',
        editOthersPosts: 'edit_others_posts',
        publishPosts: 'publish_posts',
        readPrivatePosts: 'read_private_posts',
        read: 'read',
        deletePosts: 'delete_posts',
        deletePrivatePosts: 'delete_private_posts',
        deletePublishedPosts: 'delete_published_posts',
        deleteOthersPosts: 'delete_others_posts',
        editPrivatePosts: 'edit_private_posts',
        editPublishedPosts: 'edit_published_posts' },
     mapMetaCap: true,
     taxonomies: [] } }
